language: go
go: 
 - 1.11.x

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.11" -a -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

deployment:
  tag:
    tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
    owner: xwjdsh
    commands:
      - curl -sL https://git.io/goreleaser | bash

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
